[package]
name = "nepse-data-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
clap = "3.1.6"
shrust = "0.0.7"
